### ISSUE TITLE
On Windows 11 22H2 (OS Build 22621.1702), could not find unix in os error and another related error has occurred.

### ISSUE THREAD

**Issue by MurraySobol** [TakaakiFuruse/jump-kun#28]
These are the errors I am getting:
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\murra\.cargo\registry\src\index.crates.io-6f17d22bba15001f\c2rust-build-paths-0.17.0\src\lib.rs:35:26
   |
35 |             use std::os::unix::ffi::OsStrExt;
   |                          ^^^^ could not find `unix` in `os`

   Compiling cmake v0.1.50
error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
  --> C:\Users\murra\.cargo\registry\src\index.crates.io-6f17d22bba15001f\c2rust-build-paths-0.17.0\src\lib.rs:37:20
   |
37 |             OsStr::from_bytes(path)
   |                    ^^^^^^^^^^ function or associated item not found in `OsStr`

Is there any timeframe for resolving these issues, IMO the first error: "failed to resolve: could not find `unix` in `os`" should be straight forward, scripts should NOT reference operating systems by name.
The second error: "no function or associated item named `from_bytes` found for struct `OsStr` in the current scope" is, I believe, somehow related to to the fact that I have c2rust-ast-exporter-0.16.0.crate when I think that there is a later version of this module.

Comments/suggestions are appreciated.

Murray

**Comment by TakaakiFuruse** [comment]
As I mentioned on Reame, this library is not supported on Windows OS.
